### ISSUE TITLE
create Basic Story of Paper

### ISSUE THREAD

**Issue by JulianBruns** [joachimrussig/GI_Forum_2017_Paper#5]
What do we want to tell? Where do we focus=

**Comment by joachimrussig** [comment]
Thanks Julian for setting up a basic story. 

I think we should use the description of the [Special Session](http://www.gi-forum.org/risk) as a starting point for our story. Heat stress is a serious risk, in particular for certain groups like elderly or ms patients, and urbanization and climate change are increasing that risk. So our approach is to provide tools to help those groups to reduce the heat stress in there everyday life. To achieve this goal we're using, amongst others, remote sensing data. 

Perhaps it's a good Idea to start with the abstract, because it obliges us to focus on most important statements of our paper: motivation, problem statement, approach, results, and conclusions (https://users.ece.cmu.edu/~koopman/essays/abstract.html).
